export const COMMUNES = {
  dakar: [
    { value: "plateau", label: "Plateau" },
    { value: "medina", label: "Médina" },
    { value: "grand_dakar", label: "Grand Dakar" },
    { value: "fann_point_e_amitie", label: "Fann-Point E-Amitié" },
    { value: "gueule_tapee_fass_colobane", label: "Gueule Tapée-Fass-Colobane" },
    { value: "fass_gueule_tapee_colobane", label: "Fass-Gueule Tapée-Colobane" },
    { value: "hann_bel_air", label: "Hann Bel-Air" },
    { value: "sicap_liberte", label: "Sicap-Liberté" },
    { value: "dieuppeul_derkle", label: "Dieuppeul-Derklé" },
    { value: "biscuiterie", label: "Biscuiterie" },
    { value: "hln", label: "HLM" },
    { value: "mermoz_sacre_coeur", label: "Mermoz-Sacré Cœur" },
    { value: "ouakam", label: "Ouakam" },
    { value: "ngor", label: "Ngor" },
    { value: "yoff", label: "Yoff" },
    { value: "grand_yoff", label: "Grand Yoff" },
    { value: "patte_doie", label: "Patte d'Oie" },
    { value: "parcelles_assainies", label: "Parcelles Assainies" },
    { value: "camberene", label: "Cambérène" },
  ],
  paris: [
    { value: "paris_1er", label: "Paris 1er" },
    { value: "paris_2e", label: "Paris 2e" },
    { value: "paris_3e", label: "Paris 3e" },
    { value: "paris_4e", label: "Paris 4e" },
    { value: "paris_5e", label: "Paris 5e" },
    { value: "paris_6e", label: "Paris 6e" },
    { value: "paris_7e", label: "Paris 7e" },
    { value: "paris_8e", label: "Paris 8e" },
    { value: "paris_9e", label: "Paris 9e" },
    { value: "paris_10e", label: "Paris 10e" },
    { value: "paris_11e", label: "Paris 11e" },
    { value: "paris_12e", label: "Paris 12e" },
    { value: "paris_13e", label: "Paris 13e" },
    { value: "paris_14e", label: "Paris 14e" },
    { value: "paris_15e", label: "Paris 15e" },
    { value: "paris_16e", label: "Paris 16e" },
    { value: "paris_17e", label: "Paris 17e" },
    { value: "paris_18e", label: "Paris 18e" },
    { value: "paris_19e", label: "Paris 19e" },
    { value: "paris_20e", label: "Paris 20e" },
  ],
  abidjan: [
    { value: "plateau", label: "Plateau" },
    { value: "cocody", label: "Cocody" },
    { value: "yopougon", label: "Yopougon" },
    { value: "abobo", label: "Abobo" },
    { value: "koumassi", label: "Koumassi" },
    { value: "marcory", label: "Marcory" },
    { value: "port_bouet", label: "Port-Bouët" },
    { value: "treichville", label: "Treichville" },
    { value: "adjame", label: "Adjamé" },
    { value: "attecoube", label: "Attécoubé" },
    { value: "bingerville", label: "Bingerville" },
    { value: "songon", label: "Songon" },
  ],
  // Ajoutez d'autres villes selon vos besoins
}
