export const COMMUNES = [
  // Paris
  { code: "PAR01", name: "1er arrondissement", cityCode: "PAR" },
  { code: "PAR02", name: "2ème arrondissement", cityCode: "PAR" },
  { code: "PAR03", name: "3ème arrondissement", cityCode: "PAR" },
  { code: "PAR04", name: "4ème arrondissement", cityCode: "PAR" },
  { code: "PAR05", name: "5ème arrondissement", cityCode: "PAR" },
  { code: "PAR06", name: "6ème arrondissement", cityCode: "PAR" },
  { code: "PAR07", name: "7ème arrondissement", cityCode: "PAR" },
  { code: "PAR08", name: "8ème arrondissement", cityCode: "PAR" },
  { code: "PAR09", name: "9ème arrondissement", cityCode: "PAR" },
  { code: "PAR10", name: "10ème arrondissement", cityCode: "PAR" },
  { code: "PAR11", name: "11ème arrondissement", cityCode: "PAR" },
  { code: "PAR12", name: "12ème arrondissement", cityCode: "PAR" },
  { code: "PAR13", name: "13ème arrondissement", cityCode: "PAR" },
  { code: "PAR14", name: "14ème arrondissement", cityCode: "PAR" },
  { code: "PAR15", name: "15ème arrondissement", cityCode: "PAR" },
  { code: "PAR16", name: "16ème arrondissement", cityCode: "PAR" },
  { code: "PAR17", name: "17ème arrondissement", cityCode: "PAR" },
  { code: "PAR18", name: "18ème arrondissement", cityCode: "PAR" },
  { code: "PAR19", name: "19ème arrondissement", cityCode: "PAR" },
  { code: "PAR20", name: "20ème arrondissement", cityCode: "PAR" },

  // Marseille
  { code: "MAR01", name: "1er arrondissement", cityCode: "MAR" },
  { code: "MAR02", name: "2ème arrondissement", cityCode: "MAR" },
  { code: "MAR03", name: "3ème arrondissement", cityCode: "MAR" },
  { code: "MAR04", name: "4ème arrondissement", cityCode: "MAR" },
  { code: "MAR05", name: "5ème arrondissement", cityCode: "MAR" },
  { code: "MAR06", name: "6ème arrondissement", cityCode: "MAR" },
  { code: "MAR07", name: "7ème arrondissement", cityCode: "MAR" },
  { code: "MAR08", name: "8ème arrondissement", cityCode: "MAR" },
  { code: "MAR09", name: "9ème arrondissement", cityCode: "MAR" },
  { code: "MAR10", name: "10ème arrondissement", cityCode: "MAR" },
  { code: "MAR11", name: "11ème arrondissement", cityCode: "MAR" },
  { code: "MAR12", name: "12ème arrondissement", cityCode: "MAR" },
  { code: "MAR13", name: "13ème arrondissement", cityCode: "MAR" },
  { code: "MAR14", name: "14ème arrondissement", cityCode: "MAR" },
  { code: "MAR15", name: "15ème arrondissement", cityCode: "MAR" },
  { code: "MAR16", name: "16ème arrondissement", cityCode: "MAR" },

  // Lyon
  { code: "LYO01", name: "1er arrondissement", cityCode: "LYO" },
  { code: "LYO02", name: "2ème arrondissement", cityCode: "LYO" },
  { code: "LYO03", name: "3ème arrondissement", cityCode: "LYO" },
  { code: "LYO04", name: "4ème arrondissement", cityCode: "LYO" },
  { code: "LYO05", name: "5ème arrondissement", cityCode: "LYO" },
  { code: "LYO06", name: "6ème arrondissement", cityCode: "LYO" },
  { code: "LYO07", name: "7ème arrondissement", cityCode: "LYO" },
  { code: "LYO08", name: "8ème arrondissement", cityCode: "LYO" },
  { code: "LYO09", name: "9ème arrondissement", cityCode: "LYO" },

  // Abidjan
  { code: "ABJ01", name: "Abobo", cityCode: "ABJ" },
  { code: "ABJ02", name: "Adjamé", cityCode: "ABJ" },
  { code: "ABJ03", name: "Attécoubé", cityCode: "ABJ" },
  { code: "ABJ04", name: "Cocody", cityCode: "ABJ" },
  { code: "ABJ05", name: "Koumassi", cityCode: "ABJ" },
  { code: "ABJ06", name: "Marcory", cityCode: "ABJ" },
  { code: "ABJ07", name: "Plateau", cityCode: "ABJ" },
  { code: "ABJ08", name: "Port-Bouët", cityCode: "ABJ" },
  { code: "ABJ09", name: "Treichville", cityCode: "ABJ" },
  { code: "ABJ10", name: "Yopougon", cityCode: "ABJ" },

  // Madrid
  { code: "MAD01", name: "Centro", cityCode: "MAD" },
  { code: "MAD02", name: "Arganzuela", cityCode: "MAD" },
  { code: "MAD03", name: "Retiro", cityCode: "MAD" },
  { code: "MAD04", name: "Salamanca", cityCode: "MAD" },
  { code: "MAD05", name: "Chamartín", cityCode: "MAD" },
  { code: "MAD06", name: "Tetuán", cityCode: "MAD" },
  { code: "MAD07", name: "Chamberí", cityCode: "MAD" },
  { code: "MAD08", name: "Fuencarral-El Pardo", cityCode: "MAD" },
  { code: "MAD09", name: "Moncloa-Aravaca", cityCode: "MAD" },
  { code: "MAD10", name: "Latina", cityCode: "MAD" },

  // Barcelone
  { code: "BAR01", name: "Ciutat Vella", cityCode: "BAR" },
  { code: "BAR02", name: "Eixample", cityCode: "BAR" },
  { code: "BAR03", name: "Sants-Montjuïc", cityCode: "BAR" },
  { code: "BAR04", name: "Les Corts", cityCode: "BAR" },
  { code: "BAR05", name: "Sarrià-Sant Gervasi", cityCode: "BAR" },
  { code: "BAR06", name: "Gràcia", cityCode: "BAR" },
  { code: "BAR07", name: "Horta-Guinardó", cityCode: "BAR" },
  { code: "BAR08", name: "Nou Barris", cityCode: "BAR" },
  { code: "BAR09", name: "Sant Andreu", cityCode: "BAR" },
  { code: "BAR10", name: "Sant Martí", cityCode: "BAR" },

  // Rome
  { code: "ROM01", name: "Municipio I", cityCode: "ROM" },
  { code: "ROM02", name: "Municipio II", cityCode: "ROM" },
  { code: "ROM03", name: "Municipio III", cityCode: "ROM" },
  { code: "ROM04", name: "Municipio IV", cityCode: "ROM" },
  { code: "ROM05", name: "Municipio V", cityCode: "ROM" },
  { code: "ROM06", name: "Municipio VI", cityCode: "ROM" },
  { code: "ROM07", name: "Municipio VII", cityCode: "ROM" },
  { code: "ROM08", name: "Municipio VIII", cityCode: "ROM" },
  { code: "ROM09", name: "Municipio IX", cityCode: "ROM" },
  { code: "ROM10", name: "Municipio X", cityCode: "ROM" },

  // Londres
  { code: "LON01", name: "City of London", cityCode: "LON" },
  { code: "LON02", name: "Westminster", cityCode: "LON" },
  { code: "LON03", name: "Camden", cityCode: "LON" },
  { code: "LON04", name: "Kensington and Chelsea", cityCode: "LON" },
  { code: "LON05", name: "Hammersmith and Fulham", cityCode: "LON" },
  { code: "LON06", name: "Wandsworth", cityCode: "LON" },
  { code: "LON07", name: "Lambeth", cityCode: "LON" },
  { code: "LON08", name: "Southwark", cityCode: "LON" },
  { code: "LON09", name: "Tower Hamlets", cityCode: "LON" },
  { code: "LON10", name: "Hackney", cityCode: "LON" },
];
