export const PAYS = [
  { value: "france", label: "France" },
  { value: "senegal", label: "Sénégal" },
  { value: "cote_ivoire", label: "Côte d'Ivoire" },
  { value: "cameroun", label: "Cameroun" },
  { value: "maroc", label: "Maroc" },
  { value: "algerie", label: "Algérie" },
  { value: "tunisie", label: "Tunisie" },
  { value: "mali", label: "Mali" },
  { value: "guinee", label: "Guinée" },
  { value: "benin", label: "Bénin" },
  { value: "togo", label: "Togo" },
  { value: "burkina_faso", label: "Burkina Faso" },
  { value: "nigeria", label: "Nigeria" },
  { value: "ghana", label: "Ghana" },
  { value: "gabon", label: "Gabon" },
  { value: "congo", label: "Congo" },
  { value: "rdc", label: "République Démocratique du Congo" },
  { value: "madagascar", label: "Madagascar" },
  { value: "maurice", label: "Maurice" },
  { value: "comores", label: "Comores" },
]
