export const VILLES = {
  france: [
    { value: "paris", label: "Paris" },
    { value: "marseille", label: "Marseille" },
    { value: "lyon", label: "Lyon" },
    { value: "toulouse", label: "Toulouse" },
    { value: "nice", label: "Nice" },
    { value: "nantes", label: "Nantes" },
    { value: "strasbourg", label: "Strasbourg" },
    { value: "montpellier", label: "Montpellier" },
    { value: "bordeaux", label: "Bordeaux" },
    { value: "lille", label: "Lille" },
  ],
  senegal: [
    { value: "dakar", label: "Dakar" },
    { value: "thies", label: "Thiès" },
    { value: "rufisque", label: "Rufisque" },
    { value: "kaolack", label: "Kaolack" },
    { value: "ziguinchor", label: "Ziguinchor" },
    { value: "saint_louis", label: "Saint-Louis" },
    { value: "mbour", label: "Mbour" },
    { value: "touba", label: "Touba" },
    { value: "diourbel", label: "Diourbel" },
    { value: "louga", label: "Louga" },
  ],
  cote_ivoire: [
    { value: "abidjan", label: "Abidjan" },
    { value: "bouake", label: "Bouaké" },
    { value: "daloa", label: "Daloa" },
    { value: "yamoussoukro", label: "Yamoussoukro" },
    { value: "korhogo", label: "Korhogo" },
    { value: "san_pedro", label: "San-Pédro" },
    { value: "gagnoa", label: "Gagnoa" },
    { value: "man", label: "Man" },
    { value: "divo", label: "Divo" },
    { value: "abengourou", label: "Abengourou" },
  ],
  // Ajoutez d'autres pays selon vos besoins
};

export const CITIES = [
  { code: "PAR", name: "Paris", countryCode: "FR" },
  { code: "MAR", name: "Marseille", countryCode: "FR" },
  { code: "LYO", name: "Lyon", countryCode: "FR" },
  { code: "TOU", name: "Toulouse", countryCode: "FR" },
  { code: "NIC", name: "Nice", countryCode: "FR" },
  { code: "NAN", name: "Nantes", countryCode: "FR" },
  { code: "STR", name: "Strasbourg", countryCode: "FR" },
  { code: "MON", name: "Montpellier", countryCode: "FR" },
  { code: "BOR", name: "Bordeaux", countryCode: "FR" },
  { code: "LIL", name: "Lille", countryCode: "FR" },
  { code: "ABJ", name: "Abidjan", countryCode: "CI" },
  { code: "YAM", name: "Yamoussoukro", countryCode: "CI" },
  { code: "BOU", name: "Bouaké", countryCode: "CI" },
  { code: "DAL", name: "Daloa", countryCode: "CI" },
  { code: "KOR", name: "Korhogo", countryCode: "CI" },
  { code: "SAN", name: "San Pedro", countryCode: "CI" },
  { code: "GAG", name: "Gagnoa", countryCode: "CI" },
  { code: "MAN", name: "Man", countryCode: "CI" },
  { code: "DUE", name: "Duekoué", countryCode: "CI" },
  { code: "SEG", name: "Séguéla", countryCode: "CI" },
  { code: "LON", name: "Londres", countryCode: "GB" },
  { code: "BIR", name: "Birmingham", countryCode: "GB" },
  { code: "MAN", name: "Manchester", countryCode: "GB" },
  { code: "LIV", name: "Liverpool", countryCode: "GB" },
  { code: "BRI", name: "Bristol", countryCode: "GB" },
  { code: "NEW", name: "Newcastle", countryCode: "GB" },
  { code: "NOT", name: "Nottingham", countryCode: "GB" },
  { code: "SHE", name: "Sheffield", countryCode: "GB" },
  { code: "LEE", name: "Leeds", countryCode: "GB" },
  { code: "EDI", name: "Édimbourg", countryCode: "GB" },
  { code: "MAD", name: "Madrid", countryCode: "ES" },
  { code: "BAR", name: "Barcelone", countryCode: "ES" },
  { code: "VAL", name: "Valence", countryCode: "ES" },
  { code: "SEV", name: "Séville", countryCode: "ES" },
  { code: "ZAR", name: "Saragosse", countryCode: "ES" },
  { code: "MAL", name: "Málaga", countryCode: "ES" },
  { code: "MUR", name: "Murcie", countryCode: "ES" },
  { code: "PAL", name: "Palma", countryCode: "ES" },
  { code: "LAS", name: "Las Palmas", countryCode: "ES" },
  { code: "BIL", name: "Bilbao", countryCode: "ES" },
  { code: "ROM", name: "Rome", countryCode: "IT" },
  { code: "MIL", name: "Milan", countryCode: "IT" },
  { code: "NAP", name: "Naples", countryCode: "IT" },
  { code: "TUR", name: "Turin", countryCode: "IT" },
  { code: "PAL", name: "Palerme", countryCode: "IT" },
  { code: "GEN", name: "Gênes", countryCode: "IT" },
  { code: "BOL", name: "Bologne", countryCode: "IT" },
  { code: "FLO", name: "Florence", countryCode: "IT" },
  { code: "BAR", name: "Bari", countryCode: "IT" },
  { code: "CAT", name: "Catane", countryCode: "IT" },
];
