export const VILLES = {
  france: [
    { value: "paris", label: "Paris" },
    { value: "marseille", label: "Marseille" },
    { value: "lyon", label: "Lyon" },
    { value: "toulouse", label: "Toulouse" },
    { value: "nice", label: "Nice" },
    { value: "nantes", label: "Nantes" },
    { value: "strasbourg", label: "Strasbourg" },
    { value: "montpellier", label: "Montpellier" },
    { value: "bordeaux", label: "Bordeaux" },
    { value: "lille", label: "Lille" },
  ],
  senegal: [
    { value: "dakar", label: "Dakar" },
    { value: "thies", label: "Thiès" },
    { value: "rufisque", label: "Rufisque" },
    { value: "kaolack", label: "Kaolack" },
    { value: "ziguinchor", label: "Ziguinchor" },
    { value: "saint_louis", label: "Saint-Louis" },
    { value: "mbour", label: "Mbour" },
    { value: "touba", label: "Touba" },
    { value: "diourbel", label: "Diourbel" },
    { value: "louga", label: "Louga" },
  ],
  cote_ivoire: [
    { value: "abidjan", label: "Abidjan" },
    { value: "bouake", label: "Bouaké" },
    { value: "daloa", label: "Daloa" },
    { value: "yamoussoukro", label: "Yamoussoukro" },
    { value: "korhogo", label: "Korhogo" },
    { value: "san_pedro", label: "San-Pédro" },
    { value: "gagnoa", label: "Gagnoa" },
    { value: "man", label: "Man" },
    { value: "divo", label: "Divo" },
    { value: "abengourou", label: "Abengourou" },
  ],
  // Ajoutez d'autres pays selon vos besoins
}
